name: Coverage Report

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: test
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: app/build/reports/jacoco/test/jacocoTestReport.xml,feature-semver/build/reports/jacoco/test/jacocoTestReport.xml,provider/build/reports/jacoco/test/jacocoTestReport.xml,provider-git/build/reports/jacoco/test/jacocoTestReport.xml
